# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rating_count', models.IntegerField()),
                ('students_enrolled', models.IntegerField()),
                ('what_will_i_learn', models.TextField()),
                ('requirements', models.TextField()),
                ('description', models.TextField()),
                ('preview_video_url', models.FilePathField(max_length=255, null=True)),
                ('preview_image_url', models.FilePathField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('no_lectures', models.IntegerField(null=True)),
                ('no_hours', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('level', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('preview_url', models.FilePathField(max_length=255)),
                ('video_url', models.FilePathField(max_length=255)),
                ('order_num', models.IntegerField(verbose_name=3)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order_num', models.IntegerField(verbose_name=3)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_on_demand', models.IntegerField(verbose_name=3)),
                ('supplemental_resources', models.IntegerField(verbose_name=3)),
                ('lifetime_access', models.BooleanField()),
                ('access_on_mobile', models.BooleanField()),
                ('certificate', models.BooleanField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('students', models.IntegerField(verbose_name=6)),
                ('reviews', models.IntegerField(verbose_name=5)),
                ('courses', models.IntegerField(verbose_name=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_stars', models.IntegerField(verbose_name=1)),
                ('about_the_course', models.CharField(max_length=500)),
                ('about_the_instructor', models.CharField(max_length=500)),
                ('how_course_can_improved', models.CharField(max_length=500)),
                ('review', models.TextField()),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('course_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='curriculumlecture',
            name='curriculum_section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CurriculumSection'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Language'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Subcategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='courses.Tag'),
        ),
    ]
