# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-13 00:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReviewVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.StudentReview')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(default='guroomed courses subtitle', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsection',
            name='duration',
            field=models.TimeField(default=datetime.datetime(2018, 2, 13, 6, 1, 26, 831817)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculumsection',
            name='no_lectures',
            field=models.IntegerField(default=0, verbose_name=3),
            preserve_default=False,
        ),
    ]
