# Generated by Django 2.0.2 on 2018-03-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180213_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor_id',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ManyToManyField(to='courses.Instructor'),
        ),
    ]
