# Generated by Django 2.0.2 on 2018-03-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180306_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='no_hours',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='ratings',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_enrolled',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtitle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(null=True, to='courses.Tag'),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_will_i_learn',
            field=models.TextField(null=True),
        ),
    ]
