# Generated by Django 2.0.2 on 2018-03-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180308_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('e', 'Expert'), ('a', 'All'), ('i', 'Intermediate')], default='a', max_length=20, null=True),
        ),
    ]
