# Generated by Django 2.0.2 on 2018-03-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180309_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Expert', 'Expert'), ('All', 'All'), ('Intermediate', 'Intermediate')], default='All', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='courses.Tag'),
        ),
    ]
