# Generated by Django 2.0.2 on 2018-04-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180315_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumlecture',
            name='lecture_type',
            field=models.CharField(choices=[('Video', 'Video'), ('3D-Model', '3D-Model'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
