# Generated by Django 2.0.2 on 2018-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_curriculumlecture_lecture_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumlecture',
            name='lecture_type',
            field=models.CharField(choices=[('Video', 'Video'), ('Quiz', 'Quiz'), ('3D-Model', '3D-Model'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculumlecture',
            name='preview_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curriculumlecture',
            name='video_url',
            field=models.CharField(max_length=255),
        ),
    ]
