# Generated by Django 2.0.2 on 2018-05-18 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drafts', '0008_auto_20180421_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('status', models.BooleanField()),
                ('order', models.IntegerField(verbose_name=2)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('status', models.BooleanField()),
                ('order', models.IntegerField(verbose_name=2)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name=2)),
                ('score_outof', models.IntegerField(verbose_name=2)),
                ('status', models.BooleanField()),
                ('correct_questions', models.CharField(max_length=500)),
                ('wrong_questions', models.CharField(max_length=500)),
                ('skipped_questions', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('course_section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.CurriculumSection')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quizzes'),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Quizzes'),
        ),
        migrations.AddField(
            model_name='questions',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuestionTypes'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Questions'),
        ),
    ]
