# Generated by Django 2.0.2 on 2018-04-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_auto_20180414_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=250, null=True)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('rating_count', models.IntegerField(null=True)),
                ('students_enrolled', models.IntegerField(null=True)),
                ('what_will_i_learn', models.TextField(null=True)),
                ('requirements', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('preview_video_url', models.FilePathField(max_length=255, null=True)),
                ('preview_image_url', models.FilePathField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('no_lectures', models.IntegerField(null=True)),
                ('no_hours', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('label', models.CharField(choices=[('New', 'New'), ('Bestseller', 'Bestseller')], default='New', max_length=20, null=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Expert', 'Expert'), ('All', 'All'), ('Intermediate', 'Intermediate')], default='All', max_length=20, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('course_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Language')),
                ('course_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Subcategory')),
                ('instructor', models.ManyToManyField(to='courses.Instructor')),
                ('tags', models.ManyToManyField(to='courses.Tag')),
            ],
        ),
    ]
