# Generated by Django 2.0.2 on 2018-04-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcourse',
            name='is_draft',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='draftcourse',
            name='is_reviewed',
            field=models.NullBooleanField(),
        ),
    ]
