# Generated by Django 2.0.2 on 2018-04-15 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('drafts', '0002_auto_20180414_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=300)),
                ('status', models.NullBooleanField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReasonsRejected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Course Manager', 'Course Manager'), ('Course Reviewer', 'Course Reviewer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=300)),
                ('status', models.NullBooleanField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='draftcourse',
            name='status',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='reviewedcourses',
            name='course_draft_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.DraftCourse'),
        ),
        migrations.AddField(
            model_name='reviewedcourses',
            name='reason_rejected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.ReasonsRejected'),
        ),
        migrations.AddField(
            model_name='reviewedcourses',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursesroles',
            name='draft_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.DraftCourse'),
        ),
        migrations.AddField(
            model_name='coursesroles',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='coursesroles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvedcourses',
            name='course_draft_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.DraftCourse'),
        ),
        migrations.AddField(
            model_name='approvedcourses',
            name='reason_rejected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.ReasonsRejected'),
        ),
        migrations.AddField(
            model_name='approvedcourses',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
