# Generated by Django 2.0.2 on 2018-04-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0004_auto_20180415_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewedcourses',
            name='reason_rejected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drafts.ReasonsRejected'),
        ),
    ]
