# Generated by Django 2.0.2 on 2018-04-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0005_auto_20180415_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_type', models.CharField(choices=[('Video', 'Video'), ('Quiz', 'Quiz'), ('3D-Model', '3D-Model'), ('None', 'None')], default='None', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('preview_url', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('order_num', models.IntegerField(verbose_name=3)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order_num', models.IntegerField(verbose_name=3)),
                ('no_lectures', models.IntegerField(verbose_name=3)),
                ('duration', models.DurationField()),
                ('course_draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.DraftCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_on_demand', models.IntegerField(null=True, verbose_name=3)),
                ('supplemental_resources', models.IntegerField(null=True, verbose_name=3)),
                ('lifetime_access', models.NullBooleanField()),
                ('access_on_mobile', models.NullBooleanField()),
                ('certificate', models.NullBooleanField()),
                ('course_draft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.DraftCourse')),
            ],
        ),
        migrations.RenameField(
            model_name='coursesroles',
            old_name='draft_course_id',
            new_name='course_draft_id',
        ),
        migrations.AddField(
            model_name='curriculumlecture',
            name='curriculum_section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.CurriculumSection'),
        ),
    ]
