# Generated by Django 2.0.2 on 2018-04-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0006_auto_20180416_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculumlecture',
            old_name='url',
            new_name='video_url',
        ),
    ]
