# Generated by Django 2.0.2 on 2018-04-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0007_auto_20180418_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='include',
            name='course_draft_id',
        ),
        migrations.DeleteModel(
            name='Include',
        ),
    ]
