# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tax_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('tax_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('payment_status', models.CharField(choices=[('successful', 'successful'), ('failed', 'failed')], max_length=12)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paywithpaypal.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PaypalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30, null=True)),
                ('cart', models.CharField(max_length=30, null=True)),
                ('payer_payment_method', models.CharField(max_length=30, null=True)),
                ('payer_status', models.CharField(max_length=50, null=True)),
                ('payer_email', models.CharField(max_length=255, null=True)),
                ('payer_id', models.CharField(max_length=100, null=True)),
                ('payer_country_code', models.CharField(max_length=10, null=True)),
                ('transactions_amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('transactions_currency', models.CharField(max_length=10, null=True)),
                ('payee_merchant_id', models.CharField(max_length=50, null=True)),
                ('payee_email', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('payment_mode', models.CharField(max_length=50, null=True)),
                ('reason_code', models.CharField(max_length=50, null=True)),
                ('protection_eligibility', models.CharField(max_length=50, null=True)),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paywithpaypal.Order')),
            ],
        ),
    ]
