# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywithpaypal', '0002_auto_20180226_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercourse',
            name='course_price',
            field=models.DecimalField(decimal_places=2, default=200.1, max_digits=9),
            preserve_default=False,
        ),
    ]
