# Generated by Django 2.0.2 on 2018-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paywithpaypal', '0004_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
